language: c
matrix:
  include:
    - os: osx
      env: TARGET_MACHINE=i3osx
#    - os: osx
#      env: TARGET_MACHINE=ti3osx
#    - os: osx
#      env: TARGET_MACHINE=a6osx
#    - os: osx
#      env: TARGET_MACHINE=ta6osx
    - os: linux
      env: TARGET_MACHINE=i3le
#    - os: linux
#      env: TARGET_MACHINE=ti3le
#    - os: linux
#      env: TARGET_MACHINE=a6le
#    - os: linux
#      env: TARGET_MACHINE=ta6le
dist: trusty
addons:
  apt:
    packages:
      - lib32z1
      - lib32ncurses5
      - lib32bz2
script:
  - ./configure -m=$TARGET_MACHINE && make && ( cd ${TARGET_MACHINE}/mats && make partialx 2>&1 ) | tee Make.out | grep '^matting '
