language: c
sudo: required
matrix:
  include:
    - os: osx
      env: TARGET_MACHINE=i3osx
    - os: osx
      env: TARGET_MACHINE=ti3osx
    - os: osx
      env: TARGET_MACHINE=a6osx
    - os: osx
      env: TARGET_MACHINE=ta6osx
    - os: linux
      env: TARGET_MACHINE=i3le
    - os: linux
      env: TARGET_MACHINE=ti3le
    - os: linux
      env: TARGET_MACHINE=a6le
    - os: linux
      env: TARGET_MACHINE=ta6le
install:
  - if [[ "$TARGET_MACHINE" == "i3le" || "$TARGET_MACHINE" == "ti3le" ]] ; then sudo apt-get update -y ; fi
  - if [[ "$TARGET_MACHINE" == "i3le" || "$TARGET_MACHINE" == "ti3le" ]] ; then sudo apt-get install -y lib32z1 lib32ncurses5 lib32bz2-1.0 ; fi
script:
  - ./configure -m=$TARGET_MACHINE && make && make test 2>&1 | tee Make.out | grep '^matting '
